# Generated by Django 5.2.6 on 2025-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State assigned to the agent', max_length=100, null=True),
        ),
    ]
