# Generated by Django 5.2.6 on 2025-10-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop__state_shop_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
    ]
