# Generated by Django 5.2.6 on 2025-10-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
        ('shops', '0003_remove_shop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_shops', to='accounts.agentprofile'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='accounts.storeownerprofile'),
        ),
    ]
