# Generated by Django 5.2.6 on 2025-10-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
        ('shops', '0004_alter_shop_created_by_alter_shop_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='_state',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_shops', to='accounts.agent'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='accounts.storeowner'),
        ),
    ]
