# Generated by Django 5.2.6 on 2025-10-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_rename__state_shop_state_alter_shop_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
