# Generated by Django 5.2.6 on 2025-11-09 11:31

import cloudinary.models
import shops.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_description_shop_local_government_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[shops.validators.validate_image], verbose_name='image'),
        ),
    ]
