# Generated by Django 5.2.6 on 2025-11-17 06:32

import shops.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shopphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopphoto',
            name='photo',
            field=models.ImageField(upload_to='shop_photos', validators=[shops.validators.validate_image]),
        ),
    ]
