# Generated by Django 5.2.6 on 2025-11-18 14:18

import cloudinary_storage.storage
import shops.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_shopphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopphoto',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='shop_photos', validators=[shops.validators.validate_image]),
        ),
    ]
