# Generated by Django 5.2.6 on 2025-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_alter_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
